# Generated by Django 6.0.1 on 2026-01-13 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_type', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producttype',
            old_name='nome',
            new_name='name',
        ),
    ]
