# Generated by Django 6.0.1 on 2026-01-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_type', '0002_rename_nome_producttype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttype',
            name='name',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
    ]
