# Generated by Django 6.0.1 on 2026-02-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_type', '0003_alter_producttype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttype',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
