# Generated by Django 6.0.1 on 2026-04-12 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_type', '0004_alter_producttype_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
