# Generated by Django 6.0.1 on 2026-01-27 15:27

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension
from django.conf import settings

class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_url'),
    ]

    operations = [
        UnaccentExtension() if not settings.DEBUG else migrations.RunSQL('SELECT 1'), # Isso instala a extensão no banco
    ]
