# Generated by Django 6.0.1 on 2026-01-27 15:27

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension

class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_url'),
    ]

    operations = [
        UnaccentExtension(), # Isso instala a extensão no banco
    ]
