# Generated by Django 6.0.1 on 2026-01-27 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_url'),
    ]

    operations = [
    ]
