# Generated by Django 6.0.1 on 2026-01-27 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_auto_20260127_1527'),
        ('category', '0003_auto_20260127_1528'),
    ]

    operations = [
    ]
