# Generated by Django 6.0.1 on 2026-01-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_merge_0003_auto_20260127_1527_0003_auto_20260127_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
    ]
