# Generated by Django 6.0.1 on 2026-04-12 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_family_source_category_is_active_category_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='notes',
            field=models.CharField(blank=True, default='Criada', max_length=50, null=True),
        ),
    ]
