# Generated by Django 6.0.1 on 2026-01-16 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ['entity']},
        ),
        migrations.RenameField(
            model_name='history',
            old_name='entidade',
            new_name='entity',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='ficha',
            new_name='new_tax',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='nova_tax',
            new_name='record',
        ),
    ]
