# Generated by Django 6.0.1 on 2026-04-22 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attributes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='expected_value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
